name: "PHP-CS-Fixer"

on:
    workflow_call:
        inputs:
            head_ref:
                required: true
                type: string
            repository:
                required: true
                type: string
            enable_auto_commit:
                default: false
                required: false
                type: boolean
            config_file:
                default: ".php_cs.dist"
                required: false
                type: string
            use_global_config:
                default: false
                required: false
                type: boolean
            finder_file:
                default: ".php-cs-fixer-finder.dist.php"
                required: false
                type: string
            php_version:
                default: "8.3"
                required: false
                type: string
            cs_fixer_version:
                default: "v3.91.3"
                required: false
                type: string
        secrets:
            PHP_CS_FIXER_GITHUB_TOKEN:
                required: true

jobs:
    php-cs-fixer:
        permissions:
            contents: write # for stefanzweifel/git-auto-commit-action to push code in repo
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ inputs.php_version }}

            -   name: Checkout Repository
                uses: actions/checkout@v4
                with:
                    ref: ${{ inputs.head_ref }}
                    repository: ${{ inputs.repository }}
                    token: ${{ secrets.PHP_CS_FIXER_GITHUB_TOKEN }}

            -   name: Checkout global config
                uses: actions/checkout@v4
                if: ${{ inputs.use_global_config }}
                with:
                    repository: open-dxp/workflows-collection-public
                    path: .workflows-collection-public
                    ref: "main"

            -   name: Copy global config
                if: ${{ inputs.use_global_config }}
                run: |
                    cp .workflows-collection-public/php-cs-fixer-configuration/.php-cs-fixer.dist.php .php-cs-fixer-global.php

            -   name: Verify finder file exists
                if: ${{ inputs.use_global_config }}
                run: |
                    if [ ! -f "${{ inputs.finder_file }}" ]; then
                      echo "Error: Finder file '${{ inputs.finder_file }}' not found!"
                      exit 1
                    fi

            -   name: PHP-CS-Fixer
                run: |
                  wget -q https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/${{ inputs.cs_fixer_version }}/php-cs-fixer.phar
                  php php-cs-fixer.phar --version
                  php php-cs-fixer.phar fix --config=${{ inputs.use_global_config && '.php-cs-fixer-global.php' || inputs.config_file }} --allow-risky yes

            -   name: Clean Up
                run: |
                  rm php-cs-fixer.phar
                  rm -rf .workflows-collection-public
                  rm .php-cs-fixer-global.php

            -   uses: stefanzweifel/git-auto-commit-action@v5
                if: ${{ inputs.enable_auto_commit }}
                with:
                    commit_message: Apply php-cs-fixer changes