name: 'Close stale issues'

on:
  workflow_call:

permissions:
  contents: read
  
jobs:
  stale:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 20
          days-before-issue-close: -1
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-all-milestones: true
          exempt-issue-labels: 'OpenDXP:Priority,OpenDXP:Backlog,OpenDXP:ToDo'
          remove-stale-when-updated: false
          stale-issue-label: 'PR Welcome'
          operations-per-run: 100
          stale-issue-message: >
              Thank you for reporting this issue.
              Since it hasn’t been labeled as “OpenDXP:Priority,” “OpenDXP:ToDo,” or “OpenDXP:Backlog,” we don’t plan to address it in the near future.
              If this is a bug report, please consider submitting a pull request — we’ll review it as soon as possible.
              If you’d like to contribute a new feature, please get in touch with us first so we can discuss whether it fits.
              Thanks for your understanding.
          close-issue-message: >
              This issue has been closed due to inactivity for 365 days.
              Feel free to continue the conversation or add any missing information. We’ll reopen it if necessary.
              Thank you!